import type { ProfileAnalysis } from "./types";

export const demoAnalysis: ProfileAnalysis = {
  profile: {
    username: "alex-rivera",
    name: "Alex Rivera",
    avatarUrl: "",
    profileUrl: "https://github.com/",
    bio: "Full-stack developer learning to build dependable AI products.",
  },
  stats: {
    repositories: 18,
    activeLanguages: 6,
    evidencePoints: 31,
    recentProjects: 7,
  },
  headline: "Strong builder. Your next unlock is proving reliability.",
  summary:
    "Your repositories show consistent full-stack delivery and early agent work. The highest-leverage move is to add evaluation, observability, and deployment evidence to projects you already care about.",
  skills: [
    {
      id: "frontend",
      label: "Product UI",
      category: "Build",
      score: 86,
      evidence: [
        { repo: "signal-studio", detail: "TypeScript + Next.js" },
        { repo: "trip-canvas", detail: "React interface" },
      ],
    },
    {
      id: "backend",
      label: "Backend APIs",
      category: "Systems",
      score: 74,
      evidence: [
        { repo: "signal-studio", detail: "FastAPI service" },
        { repo: "queue-kit", detail: "Python workers" },
      ],
    },
    {
      id: "agents",
      label: "AI Agents",
      category: "Intelligence",
      score: 66,
      evidence: [
        { repo: "research-loop", detail: "Tool-using agent" },
        { repo: "doc-compass", detail: "RAG pipeline" },
      ],
    },
    {
      id: "data",
      label: "Data & RAG",
      category: "Intelligence",
      score: 58,
      evidence: [{ repo: "doc-compass", detail: "Vector retrieval" }],
    },
    {
      id: "testing",
      label: "Evaluation",
      category: "Delivery",
      score: 34,
      evidence: [{ repo: "queue-kit", detail: "Basic unit tests" }],
    },
    {
      id: "delivery",
      label: "Production",
      category: "Delivery",
      score: 42,
      evidence: [{ repo: "trip-canvas", detail: "Vercel deployment" }],
    },
  ],
  focusAreas: ["Agent evaluation", "Production observability", "Failure-driven testing"],
  projects: [
    {
      name: "research-loop",
      url: "https://github.com/",
      description: "Agentic research workflow with source collection.",
      language: "Python",
      stars: 8,
      forks: 1,
      topics: ["agents", "openai", "research"],
      updatedAt: "2026-07-12T00:00:00Z",
    },
    {
      name: "signal-studio",
      url: "https://github.com/",
      description: "Full-stack analytics workspace.",
      language: "TypeScript",
      stars: 5,
      forks: 0,
      topics: ["nextjs", "fastapi", "analytics"],
      updatedAt: "2026-07-09T00:00:00Z",
    },
    {
      name: "doc-compass",
      url: "https://github.com/",
      description: "Semantic search for long documents.",
      language: "Python",
      stars: 3,
      forks: 0,
      topics: ["rag", "embeddings"],
      updatedAt: "2026-06-28T00:00:00Z",
    },
  ],
  roadmap: [
    {
      week: 1,
      title: "Define what good means",
      outcome: "Turn research-loop into a measurable agent, not a vibes-based demo.",
      project: "research-loop",
      deliverables: ["20-case eval dataset", "Success rubric", "Baseline run"],
      proof: "Commit the dataset and publish a baseline score.",
    },
    {
      week: 2,
      title: "Make failures visible",
      outcome: "Trace retrieval, tool calls, latency, and failure categories.",
      project: "research-loop",
      deliverables: ["Structured traces", "Failure taxonomy", "Run viewer"],
      proof: "Explain three failed runs using captured evidence.",
    },
    {
      week: 3,
      title: "Improve with evidence",
      outcome: "Use eval results to improve one weak behavior without regressions.",
      project: "research-loop",
      deliverables: ["Prompt experiment", "A/B results", "Regression gate"],
      proof: "Show the before/after score and the trade-off you accepted.",
    },
    {
      week: 4,
      title: "Ship the learning",
      outcome: "Package the system as a testable, recruiter-ready case study.",
      project: "research-loop",
      deliverables: ["Public demo", "Architecture note", "90-second walkthrough"],
      proof: "A new user can run the project from the README in under five minutes.",
    },
  ],
  source: "demo",
  generatedBy: "GPT-5.6",
};
